---
- name: Install Docker on Debian
  hosts: all
  become: true  # Requires elevated privileges
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install ca-certificates and curl packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create directory for Docker keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644

    - name: Add repository to Apt sources
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        create: yes
        line: "deb [arch={{ ansible_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_major_version }} stable"
        state: present

    - name: Update package lists after adding repository
      apt:
        update_cache: yes

  vars:
    docker_repo_line: "deb [arch={{ ansible_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_major_version }} stable"

